### ISSUE TITLE
Can add translations in different languages? Thanks a lot

### ISSUE THREAD

**Issue by xinguanhua** [aoe4world/data#14]

**Comment by robertvanhoesel** [comment]
You can build this data with different locales by adding it in the desired files described [here](https://github.com/aoe4world/data#:~:text=cardinal%5Carchives%5CLocaleEnglish,sga%20..%2Fsource%2Flocale%60) and changing the locale you want to use here: https://github.com/aoe4world/data/blob/main/src/attrib/translations.ts

**Comment by xinguanhua** [comment]
thanks，I should read read.me more carefully

**Comment by robertvanhoesel** [comment]
Don't worry, it's not that clear.
